
package proyectofinal;

import java.util.ArrayList;


public class PContactos extends javax.swing.JPanel {

    ArrayList<TContactos> tablacontactos = new ArrayList<TContactos>();
    
    public PContactos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new RSMaterialComponent.RSLabelTextIcon();
        jLabel1 = new javax.swing.JLabel();
        cliente = new RSMaterialComponent.RSTextFieldIconDos();
        tipo = new RSMaterialComponent.RSTextFieldIconDos();
        Banco = new javax.swing.JLabel();
        telefono = new RSMaterialComponent.RSTextFieldIconDos();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correo = new RSMaterialComponent.RSTextFieldIconDos();
        Añadir = new RSMaterialComponent.RSButtonMaterialIconDos();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojeru_san.complementos.RSTableMetro();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setForeground(new java.awt.Color(122, 202, 170));
        Titulo.setText(" Contactos");
        Titulo.setColorIcon(new java.awt.Color(122, 202, 170));
        Titulo.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        Titulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACT_PHONE);
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 369, 68));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 99, 92));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        cliente.setForeground(new java.awt.Color(0, 0, 0));
        cliente.setBorderColor(new java.awt.Color(122, 202, 170));
        cliente.setColorIcon(new java.awt.Color(122, 202, 170));
        cliente.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        cliente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        cliente.setPhColor(new java.awt.Color(79, 183, 145));
        cliente.setPlaceholder("Nombre");
        cliente.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        cliente.setSelectionColor(new java.awt.Color(79, 183, 145));
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 109, -1, -1));

        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setBorderColor(new java.awt.Color(122, 202, 170));
        tipo.setColorIcon(new java.awt.Color(122, 202, 170));
        tipo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        tipo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON_PIN_CIRCLE);
        tipo.setPhColor(new java.awt.Color(79, 183, 145));
        tipo.setPlaceholder("Tipo");
        tipo.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        tipo.setSelectionColor(new java.awt.Color(79, 183, 145));
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 109, 186, -1));

        Banco.setBackground(new java.awt.Color(0, 0, 0));
        Banco.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Banco.setForeground(new java.awt.Color(26, 99, 92));
        Banco.setText("Tipo");
        jPanel1.add(Banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        telefono.setForeground(new java.awt.Color(0, 0, 0));
        telefono.setBorderColor(new java.awt.Color(122, 202, 170));
        telefono.setColorIcon(new java.awt.Color(122, 202, 170));
        telefono.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        telefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CALL);
        telefono.setPhColor(new java.awt.Color(79, 183, 145));
        telefono.setPlaceholder("Telefono");
        telefono.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        telefono.setSelectionColor(new java.awt.Color(79, 183, 145));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 109, 147, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 99, 92));
        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 86, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 99, 92));
        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 86, -1, -1));

        correo.setForeground(new java.awt.Color(0, 0, 0));
        correo.setBorderColor(new java.awt.Color(122, 202, 170));
        correo.setColorIcon(new java.awt.Color(122, 202, 170));
        correo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        correo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        correo.setPhColor(new java.awt.Color(79, 183, 145));
        correo.setPlaceholder("Correo");
        correo.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        correo.setSelectionColor(new java.awt.Color(79, 183, 145));
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 227, -1));

        Añadir.setText(" Añadir");
        Añadir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        jPanel1.add(Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 163, 128, -1));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAltoHead(60);
        tabla.setColorBackgoundHead(new java.awt.Color(122, 202, 170));
        tabla.setColorFilasBackgound1(new java.awt.Color(207, 226, 219));
        tabla.setColorFilasBackgound2(new java.awt.Color(177, 212, 199));
        tabla.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabla.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabla.setColorSelBackgound(new java.awt.Color(68, 124, 102));
        tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla.setFuenteFilas(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabla.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tabla.setFuenteHead(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setRowHeight(30);
        tabla.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tabla.setShowGrid(false);
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 820, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed

        //if (calendario.getDatoFecha() != null) {
            //String format = "dd/MM/yyyy";
            //Date fecha = calendario.getDatoFecha();
            //SimpleDateFormat dateFormat = new SimpleDateFormat(format);
            //}

        TContactos tabla = new TContactos(cliente.getText(), tipo.getText(), telefono.getText(), correo.getText());
        tablacontactos.add(tabla);

        mostrar();

        cliente.setText(" ");
        cliente.setPlaceholder("Nombre");

        tipo.setText(" ");
        tipo.setPlaceholder("Tipo");

        telefono.setText(" ");
        telefono.setPlaceholder("Telefono");

        correo.setText(" ");
        correo.setPlaceholder("Correo");
    }//GEN-LAST:event_AñadirActionPerformed

    public void mostrar() 
    {
        
        String matrix[][] = new String[tablacontactos.size()][4];
        
        for(int x = 0; x<tablacontactos.size(); x++)
        {
            matrix[x][0] = tablacontactos.get(x).getClientes();
            matrix[x][1] = tablacontactos.get(x).getTipo();
            matrix[x][2] = tablacontactos.get(x).getTelefono();
            matrix[x][3] = tablacontactos.get(x).getCorreo();
        }
        
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
                
            new String [] {
                "Nombre", "Tipo", "Telefono", "Correo"
            }
                
        ));
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos Añadir;
    private javax.swing.JLabel Banco;
    public RSMaterialComponent.RSLabelTextIcon Titulo;
    public RSMaterialComponent.RSTextFieldIconDos cliente;
    public RSMaterialComponent.RSTextFieldIconDos correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public rojeru_san.complementos.RSTableMetro tabla;
    public RSMaterialComponent.RSTextFieldIconDos telefono;
    public RSMaterialComponent.RSTextFieldIconDos tipo;
    // End of variables declaration//GEN-END:variables

    static class RSPanelsSlider {

        static Object DIRECT;

        public RSPanelsSlider() {
        }
    }
}
