/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author Lord Shadow
 */
public class PInfo extends javax.swing.JPanel {

    /**
     * Creates new form PCitas
     */
    public PInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelS = new javax.swing.JPanel();
        rSLabelImage4 = new rojeru_san.rslabel.RSLabelImage();
        rSLabelImage5 = new rojeru_san.rslabel.RSLabelImage();
        rSLabelImage6 = new rojeru_san.rslabel.RSLabelImage();
        FondoP = new javax.swing.JPanel();
        BordeI = new javax.swing.JPanel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        P1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P6 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelS.setBackground(new java.awt.Color(122, 202, 170));
        PanelS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Escudo-B1.png"))); // NOI18N
        PanelS.add(rSLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ravenB.png"))); // NOI18N
        PanelS.add(rSLabelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 110));

        rSLabelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-fie-B.png"))); // NOI18N
        PanelS.add(rSLabelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, -1));

        jPanel1.add(PanelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 710, 140));

        FondoP.setBackground(new java.awt.Color(242, 242, 242));
        FondoP.setBorder(new rojeru_san.extras.FlatShadowBorder());
        FondoP.setForeground(new java.awt.Color(255, 255, 255));

        BordeI.setBackground(new java.awt.Color(81, 162, 146));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMG_20191128_134843.jpg"))); // NOI18N

        javax.swing.GroupLayout BordeILayout = new javax.swing.GroupLayout(BordeI);
        BordeI.setLayout(BordeILayout);
        BordeILayout.setHorizontalGroup(
            BordeILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BordeILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        BordeILayout.setVerticalGroup(
            BordeILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BordeILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        P1.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P1.setForeground(new java.awt.Color(0, 0, 0));
        P1.setText("Autor:");

        P2.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P2.setForeground(new java.awt.Color(0, 0, 0));
        P2.setText("Carlos Alberto Tavera Arteaga");
        P2.setToolTipText("");

        P4.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P4.setForeground(new java.awt.Color(0, 0, 0));
        P4.setText("Materia:");

        P5.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P5.setForeground(new java.awt.Color(0, 0, 0));
        P5.setText("Programación de Computadoras 2");
        P5.setToolTipText("");

        P3.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P3.setForeground(new java.awt.Color(0, 0, 0));
        P3.setText("Ingeniería en Sistemas Computacionales");
        P3.setToolTipText("");

        P6.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        P6.setForeground(new java.awt.Color(0, 0, 0));
        P6.setText("Grupo 303");
        P6.setToolTipText("");

        javax.swing.GroupLayout FondoPLayout = new javax.swing.GroupLayout(FondoP);
        FondoP.setLayout(FondoPLayout);
        FondoPLayout.setHorizontalGroup(
            FondoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(BordeI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FondoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P2)
                    .addComponent(P1)
                    .addComponent(P3)
                    .addComponent(P4)
                    .addComponent(P6)
                    .addComponent(P5))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        FondoPLayout.setVerticalGroup(
            FondoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(FondoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FondoPLayout.createSequentialGroup()
                        .addComponent(P1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P3)
                        .addGap(18, 18, 18)
                        .addComponent(P4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P5)
                        .addGap(7, 7, 7)
                        .addComponent(P6))
                    .addComponent(BordeI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jPanel1.add(FondoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 750, 400));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(122, 202, 170));
        Titulo.setText("Información");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 294, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BordeI;
    public javax.swing.JPanel FondoP;
    public javax.swing.JLabel P1;
    public javax.swing.JLabel P2;
    public javax.swing.JLabel P3;
    public javax.swing.JLabel P4;
    public javax.swing.JLabel P5;
    public javax.swing.JLabel P6;
    public javax.swing.JPanel PanelS;
    public javax.swing.JLabel Titulo;
    public javax.swing.JPanel jPanel1;
    public rojerusan.RSLabelImage rSLabelImage1;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage4;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage5;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage6;
    // End of variables declaration//GEN-END:variables

    static class RSPanelsSlider {

        static Object DIRECT;

        public RSPanelsSlider() {
        }
    }
}
