
package proyectofinal;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import rojerusan.RSPanelsSlider;

public class PPrincipal extends javax.swing.JFrame {
   
    public PPrincipal() {
        
        
        initComponents();
        
        this.setLocationRelativeTo(null); //Centrar
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Icono.png")));
        
           
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelLado = new rspanelgradiente.RSPanelGradiente();
        FPerfil = new rojerusan.RSPanelCircleImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BSalir = new RSMaterialComponent.RSButtonMaterialIconUno();
        BCitas = new RSMaterialComponent.RSButtonMaterialIconUno();
        BExpedientes = new RSMaterialComponent.RSButtonMaterialIconUno();
        BFirmas = new RSMaterialComponent.RSButtonMaterialIconUno();
        BContactos = new RSMaterialComponent.RSButtonMaterialIconUno();
        BInfo = new RSMaterialComponent.RSButtonMaterialIconUno();
        Panel = new rojerusan.RSPanelsSlider();
        PCitas1 = new proyectofinal.PCitas();
        PExpedientes1 = new proyectofinal.PExpedientes();
        PFirmas1 = new proyectofinal.PFirmas();
        PContactos1 = new proyectofinal.PContactos();
        PInfo1 = new proyectofinal.PInfo();
        MenuBar = new rojerusan.RSMenuBar();
        TemasM = new javax.swing.JMenu();
        ModoOscuro = new javax.swing.JMenuItem();
        ModoClaro = new javax.swing.JMenuItem();
        CalendarioM = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        PanelLado.setColorPrimario(new java.awt.Color(122, 202, 196));
        PanelLado.setColorSecundario(new java.awt.Color(122, 202, 196));
        PanelLado.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);
        PanelLado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FPerfil.setColorBorde(new java.awt.Color(73, 160, 139));
        FPerfil.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pantera.png"))); // NOI18N

        javax.swing.GroupLayout FPerfilLayout = new javax.swing.GroupLayout(FPerfil);
        FPerfil.setLayout(FPerfilLayout);
        FPerfilLayout.setHorizontalGroup(
            FPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        FPerfilLayout.setVerticalGroup(
            FPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        PanelLado.add(FPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alt + 2");
        PanelLado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 40, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alt + I");
        PanelLado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 40, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alt +1");
        PanelLado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 40, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alt + 3");
        PanelLado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 40, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alt + S");
        PanelLado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 40, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alt + 4");
        PanelLado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 40, 40));

        BSalir.setBackground(new java.awt.Color(122, 202, 196));
        BSalir.setMnemonic('S');
        BSalir.setText("   Salir");
        BSalir.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BSalir.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        PanelLado.add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 270, 60));

        BCitas.setBackground(new java.awt.Color(122, 202, 196));
        BCitas.setMnemonic('1');
        BCitas.setText("    Citas                      ");
        BCitas.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BCitas.setEffectButton(null);
        BCitas.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BCitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BCitas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        BCitas.setSelected(true);
        BCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCitasActionPerformed(evt);
            }
        });
        BCitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BCitasKeyPressed(evt);
            }
        });
        PanelLado.add(BCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 60));

        BExpedientes.setBackground(new java.awt.Color(122, 202, 196));
        BExpedientes.setMnemonic('2');
        BExpedientes.setText("    Expedientes");
        BExpedientes.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BExpedientes.setEffectButton(null);
        BExpedientes.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BExpedientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BExpedientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        BExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExpedientesActionPerformed(evt);
            }
        });
        PanelLado.add(BExpedientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 60));

        BFirmas.setBackground(new java.awt.Color(122, 202, 196));
        BFirmas.setMnemonic('3');
        BFirmas.setText("    Firmas");
        BFirmas.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BFirmas.setEffectButton(null);
        BFirmas.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BFirmas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BFirmas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BORDER_COLOR);
        BFirmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFirmasActionPerformed(evt);
            }
        });
        PanelLado.add(BFirmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 60));

        BContactos.setBackground(new java.awt.Color(122, 202, 196));
        BContactos.setMnemonic('4');
        BContactos.setText("    Contactos");
        BContactos.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BContactos.setEffectButton(null);
        BContactos.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BContactos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BContactos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACT_PHONE);
        BContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BContactosActionPerformed(evt);
            }
        });
        PanelLado.add(BContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, 60));

        BInfo.setBackground(new java.awt.Color(122, 202, 196));
        BInfo.setMnemonic('I');
        BInfo.setText("   Información");
        BInfo.setBackgroundHover(new java.awt.Color(76, 161, 141));
        BInfo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        BInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BInfo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HELP);
        BInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInfoActionPerformed(evt);
            }
        });
        PanelLado.add(BInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 270, 60));

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        PCitas1.setName("PCitas1"); // NOI18N
        Panel.add(PCitas1, "card2");

        PExpedientes1.setName("PExpedientes1"); // NOI18N
        Panel.add(PExpedientes1, "card3");

        PFirmas1.setName("PFirmas1"); // NOI18N
        Panel.add(PFirmas1, "card4");

        PContactos1.setName("PContactos1"); // NOI18N
        Panel.add(PContactos1, "card5");

        PInfo1.setForeground(new java.awt.Color(255, 255, 255));
        PInfo1.setName("PInfo1"); // NOI18N
        Panel.add(PInfo1, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelLado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelLado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuBar.setBackground(new java.awt.Color(122, 202, 196));
        MenuBar.setForeground(new java.awt.Color(255, 255, 255));
        MenuBar.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N

        TemasM.setBackground(new java.awt.Color(255, 255, 255));
        TemasM.setBorder(null);
        TemasM.setForeground(new java.awt.Color(255, 255, 255));
        TemasM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/outline_palette_white_24dp.png"))); // NOI18N
        TemasM.setText(" Temas");
        TemasM.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        TemasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemasMActionPerformed(evt);
            }
        });

        ModoOscuro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ModoOscuro.setText("Modo Oscuro");
        ModoOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModoOscuroActionPerformed(evt);
            }
        });
        TemasM.add(ModoOscuro);

        ModoClaro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ModoClaro.setText("Modo Claro");
        ModoClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModoClaroActionPerformed(evt);
            }
        });
        TemasM.add(ModoClaro);

        MenuBar.add(TemasM);

        CalendarioM.setBackground(new java.awt.Color(255, 255, 255));
        CalendarioM.setBorder(null);
        CalendarioM.setForeground(new java.awt.Color(255, 255, 255));
        CalendarioM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/outline_event_white_24dp.png"))); // NOI18N
        CalendarioM.setText("Calendario");
        CalendarioM.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Calendario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        CalendarioM.add(jMenuItem2);

        MenuBar.add(CalendarioM);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    

    
    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BSalirActionPerformed
   
    private void BCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCitasActionPerformed
        if(!BCitas.isSelected()){
            BCitas.setSelected(true);
            BExpedientes.setSelected(false);
            BFirmas.setSelected(false);
            BContactos.setSelected(false);
            BInfo.setSelected(false);                      
          
            Panel.slidPanel(1, PCitas1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BCitasActionPerformed

    private void BExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExpedientesActionPerformed
        if(!BExpedientes.isSelected()){
            BCitas.setSelected(false);
            BExpedientes.setSelected(true);
            BFirmas.setSelected(false);
            BContactos.setSelected(false);
            BInfo.setSelected(false);                      
          
            Panel.slidPanel(1, PExpedientes1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BExpedientesActionPerformed

    private void BFirmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFirmasActionPerformed
        if(!BFirmas.isSelected()){
            BCitas.setSelected(false);
            BExpedientes.setSelected(false);
            BFirmas.setSelected(true);
            BContactos.setSelected(false);
            BInfo.setSelected(false);                      
          
            Panel.slidPanel(1, PFirmas1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BFirmasActionPerformed

    private void BContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BContactosActionPerformed
        if(!BContactos.isSelected()){
            BCitas.setSelected(false);
            BExpedientes.setSelected(false);
            BFirmas.setSelected(false);
            BContactos.setSelected(true);
            BInfo.setSelected(false);                      
          
            Panel.slidPanel(1, PContactos1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BContactosActionPerformed

    private void BInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInfoActionPerformed
       if(!BInfo.isSelected()){
            BCitas.setSelected(false);
            BExpedientes.setSelected(false);
            BFirmas.setSelected(false);
            BContactos.setSelected(false);
            BInfo.setSelected(true);                      
          
            Panel.slidPanel(1, PInfo1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BInfoActionPerformed
    
    
    private void BCitasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BCitasKeyPressed
  
        if(evt.getKeyCode() == KeyEvent.VK_F1){
            //BCitas.doClick();
            BCitas.setSelected(true);
           
        }
        
    }//GEN-LAST:event_BCitasKeyPressed

    private void TemasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemasMActionPerformed
       
    }//GEN-LAST:event_TemasMActionPerformed
      
    
    //Cambiar colores:
       
    //============================================================================
       //Modo Oscuro 1 
    
        //VERDE          #00867d
        //VERDE OSCURO   #005851
        //FONDO          #16252b
    
    private void ModoOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModoOscuroActionPerformed
        PanelLado.setColorPrimario(Color.decode("#00867d"));
        PanelLado.setColorSecundario(Color.decode("#00867d"));
        jPanel1.setBackground(Color.decode("#16252b"));
        MenuBar.setBackground(Color.decode("#00867d"));
        FPerfil.setColorBorde(Color.decode("#005851"));
        
        BCitas.setBackground(Color.decode("#00867d"));
        BCitas.setBackgroundHover(Color.decode("#005851"));
        
        BExpedientes.setBackground(Color.decode("#00867d"));
        BExpedientes.setBackgroundHover(Color.decode("#005851"));
        
        BFirmas.setBackground(Color.decode("#00867d"));
        BFirmas.setBackgroundHover(Color.decode("#005851"));
        
        BContactos.setBackground(Color.decode("#00867d"));
        BContactos.setBackgroundHover(Color.decode("#005851"));
        
        BInfo.setBackground(Color.decode("#00867d"));
        BInfo.setBackgroundHover(Color.decode("#005851"));
        
        BSalir.setBackground(Color.decode("#00867d"));
        BSalir.setBackgroundHover(Color.decode("#005851"));
        
    
        
       //Citas
        PCitas1.jPanel1.setBackground(Color.decode("#16252b"));
        PCitas1.cliente.setBackground(Color.decode("#16252b"));
        PCitas1.lugar.setBackground(Color.decode("#16252b"));
        PCitas1.fecha.setBackground(Color.decode("#16252b"));
        PCitas1.notas.setBackground(Color.decode("#16252b"));
        PCitas1.Titulo.setForeground(Color.decode("#00867d"));
        PCitas1.Titulo.setColorIcon(Color.decode("#00867d"));
        
        PCitas1.cliente.setBorderColor(Color.decode("#00867d"));
        PCitas1.cliente.setColorIcon(Color.decode("#00867d"));
        PCitas1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.lugar.setBorderColor(Color.decode("#00867d"));
        PCitas1.lugar.setColorIcon(Color.decode("#00867d"));
        PCitas1.lugar.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.fecha.setBorderColor(Color.decode("#00867d"));
        PCitas1.fecha.setColorIcon(Color.decode("#00867d"));
        PCitas1.fecha.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.notas.setBorderColor(Color.decode("#00867d"));
        PCitas1.notas.setColorIcon(Color.decode("#00867d"));
        PCitas1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.tabla.setColorBackgoundHead(Color.decode("#005851"));
        PCitas1.tabla.setColorFilasBackgound1(Color.decode("#00867d"));
        PCitas1.tabla.setColorFilasBackgound2(Color.decode("#4db6ac"));
        PCitas1.tabla.setColorSelBackgound(Color.decode("#005851"));
        PCitas1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       
       //Expedientes
        PExpedientes1.jPanel1.setBackground(Color.decode("#16252b"));
        PExpedientes1.cliente.setBackground(Color.decode("#16252b"));
        PExpedientes1.banco.setBackground(Color.decode("#16252b"));
        PExpedientes1.estado.setBackground(Color.decode("#16252b"));
        PExpedientes1.notas.setBackground(Color.decode("#16252b"));
        PExpedientes1.Titulo.setForeground(Color.decode("#00867d"));
        PExpedientes1.Titulo.setColorIcon(Color.decode("#00867d"));
        
        PExpedientes1.cliente.setBorderColor(Color.decode("#00867d"));
        PExpedientes1.cliente.setColorIcon(Color.decode("#00867d"));
        PExpedientes1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.banco.setBorderColor(Color.decode("#00867d"));
        PExpedientes1.banco.setColorIcon(Color.decode("#00867d"));
        PExpedientes1.banco.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.estado.setBorderColor(Color.decode("#00867d"));
        PExpedientes1.estado.setColorIcon(Color.decode("#00867d"));
        PExpedientes1.estado.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.notas.setBorderColor(Color.decode("#00867d"));
        PExpedientes1.notas.setColorIcon(Color.decode("#00867d"));
        PExpedientes1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.tabla.setColorBackgoundHead(Color.decode("#005851"));
        PExpedientes1.tabla.setColorFilasBackgound1(Color.decode("#00867d"));
        PExpedientes1.tabla.setColorFilasBackgound2(Color.decode("#4db6ac"));
        PExpedientes1.tabla.setColorSelBackgound(Color.decode("#005851"));
        PExpedientes1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
        
       //Firmas
       
        PFirmas1.jPanel1.setBackground(Color.decode("#16252b"));
        PFirmas1.cliente.setBackground(Color.decode("#16252b"));
        PFirmas1.notaria.setBackground(Color.decode("#16252b"));
        PFirmas1.fecha.setBackground(Color.decode("#16252b"));
        PFirmas1.notas.setBackground(Color.decode("#16252b"));
        PFirmas1.Titulo.setForeground(Color.decode("#00867d"));
        PFirmas1.Titulo.setColorIcon(Color.decode("#00867d"));
        
        PFirmas1.cliente.setBorderColor(Color.decode("#00867d"));
        PFirmas1.cliente.setColorIcon(Color.decode("#00867d"));
        PFirmas1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.notaria.setBorderColor(Color.decode("#00867d"));
        PFirmas1.notaria.setColorIcon(Color.decode("#00867d"));
        PFirmas1.notaria.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.fecha.setBorderColor(Color.decode("#00867d"));
        PFirmas1.fecha.setColorIcon(Color.decode("#00867d"));
        PFirmas1.fecha.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.notas.setBorderColor(Color.decode("#00867d"));
        PFirmas1.notas.setColorIcon(Color.decode("#00867d"));
        PFirmas1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.tabla.setColorBackgoundHead(Color.decode("#005851"));
        PFirmas1.tabla.setColorFilasBackgound1(Color.decode("#00867d"));
        PFirmas1.tabla.setColorFilasBackgound2(Color.decode("#4db6ac"));
        PFirmas1.tabla.setColorSelBackgound(Color.decode("#005851"));
        PFirmas1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       //Contactos
       
        PContactos1.jPanel1.setBackground(Color.decode("#16252b"));
        PContactos1.cliente.setBackground(Color.decode("#16252b"));
        PContactos1.tipo.setBackground(Color.decode("#16252b"));
        PContactos1.telefono.setBackground(Color.decode("#16252b"));
        PContactos1.correo.setBackground(Color.decode("#16252b"));
        PContactos1.Titulo.setForeground(Color.decode("#00867d"));
        PContactos1.Titulo.setColorIcon(Color.decode("#00867d"));
        
        PContactos1.cliente.setBorderColor(Color.decode("#00867d"));
        PContactos1.cliente.setColorIcon(Color.decode("#00867d"));
        PContactos1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.tipo.setBorderColor(Color.decode("#00867d"));
        PContactos1.tipo.setColorIcon(Color.decode("#00867d"));
        PContactos1.tipo.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.telefono.setBorderColor(Color.decode("#00867d"));
        PContactos1.telefono.setColorIcon(Color.decode("#00867d"));
        PContactos1.telefono.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.correo.setBorderColor(Color.decode("#00867d"));
        PContactos1.correo.setColorIcon(Color.decode("#00867d"));
        PContactos1.correo.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.tabla.setColorBackgoundHead(Color.decode("#005851"));
        PContactos1.tabla.setColorFilasBackgound1(Color.decode("#00867d"));
        PContactos1.tabla.setColorFilasBackgound2(Color.decode("#4db6ac"));
        PContactos1.tabla.setColorSelBackgound(Color.decode("#005851"));
        PContactos1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       //Info
       
        PInfo1.jPanel1.setBackground(Color.decode("#16252b"));
              
        PCitas1.Titulo.setForeground(Color.decode("#00867d"));
        PCitas1.Titulo.setColorIcon(Color.decode("#00867d"));
        
        PInfo1.PanelS.setBackground(Color.decode("#00867d"));
        PInfo1.BordeI.setBackground(Color.decode("#00867d"));
        
        PInfo1.FondoP.setBackground(Color.decode("#3d4d54"));   
        
        PInfo1.P1.setForeground(Color.decode("#f5f5f5"));
        PInfo1.P2.setForeground(Color.decode("#f5f5f5"));
        PInfo1.P3.setForeground(Color.decode("#f5f5f5"));
        PInfo1.P4.setForeground(Color.decode("#f5f5f5"));
        PInfo1.P5.setForeground(Color.decode("#f5f5f5"));
        PInfo1.P6.setForeground(Color.decode("#f5f5f5"));
        
    }
             
    //============================================================================
    
    
    {
        
    }//GEN-LAST:event_ModoOscuroActionPerformed
   
    //=================     HERRAMIENTAS          ==================
    
    //CALENDARIO
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Calendario cal = new Calendario();
        cal.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    //============================================================================
       //Modo Claro 1 
    
        //VERDE          #7ACAC4
        //VERDE OSCURO   #4CA18D
        //FONDO          #FFFFFF
    
    private void ModoClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModoClaroActionPerformed
        
        PanelLado.setColorPrimario(Color.decode("#7ACAC4"));
        PanelLado.setColorSecundario(Color.decode("#7ACAC4"));
        jPanel1.setBackground(Color.decode("#FFFFFF"));
        MenuBar.setBackground(Color.decode("#7ACAC4"));
        FPerfil.setColorBorde(Color.decode("#4CA18D"));
        
        BCitas.setBackground(Color.decode("#7ACAC4"));
        BCitas.setBackgroundHover(Color.decode("#4CA18D"));
        
        BExpedientes.setBackground(Color.decode("#7ACAC4"));
        BExpedientes.setBackgroundHover(Color.decode("#4CA18D"));
        
        BFirmas.setBackground(Color.decode("#7ACAC4"));
        BFirmas.setBackgroundHover(Color.decode("#4CA18D"));
        
        BContactos.setBackground(Color.decode("#7ACAC4"));
        BContactos.setBackgroundHover(Color.decode("#4CA18D"));
        
        BInfo.setBackground(Color.decode("#7ACAC4"));
        BInfo.setBackgroundHover(Color.decode("#4CA18D"));
        
        BSalir.setBackground(Color.decode("#7ACAC4"));
        BSalir.setBackgroundHover(Color.decode("#4CA18D"));
        
    
        
       //Citas
        PCitas1.jPanel1.setBackground(Color.decode("#FFFFFF"));
        PCitas1.cliente.setBackground(Color.decode("#FFFFFF"));
        PCitas1.lugar.setBackground(Color.decode("#FFFFFF"));
        PCitas1.fecha.setBackground(Color.decode("#FFFFFF"));
        PCitas1.notas.setBackground(Color.decode("#FFFFFF"));
        PCitas1.Titulo.setForeground(Color.decode("#7ACAC4"));
        PCitas1.Titulo.setColorIcon(Color.decode("#7ACAC4"));
        
        PCitas1.cliente.setBorderColor(Color.decode("#7ACAC4"));
        PCitas1.cliente.setColorIcon(Color.decode("#7ACAC4"));
        PCitas1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.lugar.setBorderColor(Color.decode("#7ACAC4"));
        PCitas1.lugar.setColorIcon(Color.decode("#7ACAC4"));
        PCitas1.lugar.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.fecha.setBorderColor(Color.decode("#7ACAC4"));
        PCitas1.fecha.setColorIcon(Color.decode("#7ACAC4"));
        PCitas1.fecha.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.notas.setBorderColor(Color.decode("#7ACAC4"));
        PCitas1.notas.setColorIcon(Color.decode("#7ACAC4"));
        PCitas1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PCitas1.tabla.setColorBackgoundHead(Color.decode("#4CA18D"));
        PCitas1.tabla.setColorFilasBackgound1(Color.decode("#CFE2DB"));
        PCitas1.tabla.setColorFilasBackgound2(Color.decode("#B1D4C7"));
        PCitas1.tabla.setColorSelBackgound(Color.decode("#4CA18D"));
        PCitas1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       
       //Expedientes
        PExpedientes1.jPanel1.setBackground(Color.decode("#FFFFFF"));
        PExpedientes1.cliente.setBackground(Color.decode("#FFFFFF"));
        PExpedientes1.banco.setBackground(Color.decode("#FFFFFF"));
        PExpedientes1.estado.setBackground(Color.decode("#FFFFFF"));
        PExpedientes1.notas.setBackground(Color.decode("#FFFFFF"));
        PExpedientes1.Titulo.setForeground(Color.decode("#7ACAC4"));
        PExpedientes1.Titulo.setColorIcon(Color.decode("#7ACAC4"));
        
        PExpedientes1.cliente.setBorderColor(Color.decode("#7ACAC4"));
        PExpedientes1.cliente.setColorIcon(Color.decode("#7ACAC4"));
        PExpedientes1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.banco.setBorderColor(Color.decode("#7ACAC4"));
        PExpedientes1.banco.setColorIcon(Color.decode("#7ACAC4"));
        PExpedientes1.banco.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.estado.setBorderColor(Color.decode("#7ACAC4"));
        PExpedientes1.estado.setColorIcon(Color.decode("#7ACAC4"));
        PExpedientes1.estado.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.notas.setBorderColor(Color.decode("#7ACAC4"));
        PExpedientes1.notas.setColorIcon(Color.decode("#7ACAC4"));
        PExpedientes1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PExpedientes1.tabla.setColorBackgoundHead(Color.decode("#4CA18D"));
        PExpedientes1.tabla.setColorFilasBackgound1(Color.decode("#CFE2DB"));
        PExpedientes1.tabla.setColorFilasBackgound2(Color.decode("#B1D4C7"));
        PExpedientes1.tabla.setColorSelBackgound(Color.decode("#4CA18D"));
        PExpedientes1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
        
       //Firmas
       
        PFirmas1.jPanel1.setBackground(Color.decode("#FFFFFF"));
        PFirmas1.cliente.setBackground(Color.decode("#FFFFFF"));
        PFirmas1.notaria.setBackground(Color.decode("#FFFFFF"));
        PFirmas1.fecha.setBackground(Color.decode("#FFFFFF"));
        PFirmas1.notas.setBackground(Color.decode("#FFFFFF"));
        PFirmas1.Titulo.setForeground(Color.decode("#7ACAC4"));
        PFirmas1.Titulo.setColorIcon(Color.decode("#7ACAC4"));
        
        PFirmas1.cliente.setBorderColor(Color.decode("#7ACAC4"));
        PFirmas1.cliente.setColorIcon(Color.decode("#7ACAC4"));
        PFirmas1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.notaria.setBorderColor(Color.decode("#7ACAC4"));
        PFirmas1.notaria.setColorIcon(Color.decode("#7ACAC4"));
        PFirmas1.notaria.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.fecha.setBorderColor(Color.decode("#7ACAC4"));
        PFirmas1.fecha.setColorIcon(Color.decode("#7ACAC4"));
        PFirmas1.fecha.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.notas.setBorderColor(Color.decode("#7ACAC4"));
        PFirmas1.notas.setColorIcon(Color.decode("#7ACAC4"));
        PFirmas1.notas.setForeground(Color.decode("#f5f5f5"));
        
        PFirmas1.tabla.setColorBackgoundHead(Color.decode("#4CA18D"));
        PFirmas1.tabla.setColorFilasBackgound1(Color.decode("#CFE2DB"));
        PFirmas1.tabla.setColorFilasBackgound2(Color.decode("#B1D4C7"));
        PFirmas1.tabla.setColorSelBackgound(Color.decode("#4CA18D"));
        PFirmas1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       //Contactos
       
        PContactos1.jPanel1.setBackground(Color.decode("#FFFFFF"));
        PContactos1.cliente.setBackground(Color.decode("#FFFFFF"));
        PContactos1.tipo.setBackground(Color.decode("#FFFFFF"));
        PContactos1.telefono.setBackground(Color.decode("#FFFFFF"));
        PContactos1.correo.setBackground(Color.decode("#FFFFFF"));
        PContactos1.Titulo.setForeground(Color.decode("#7ACAC4"));
        PContactos1.Titulo.setColorIcon(Color.decode("#7ACAC4"));
        
        PContactos1.cliente.setBorderColor(Color.decode("#7ACAC4"));
        PContactos1.cliente.setColorIcon(Color.decode("#7ACAC4"));
        PContactos1.cliente.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.tipo.setBorderColor(Color.decode("#7ACAC4"));
        PContactos1.tipo.setColorIcon(Color.decode("#7ACAC4"));
        PContactos1.tipo.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.telefono.setBorderColor(Color.decode("#7ACAC4"));
        PContactos1.telefono.setColorIcon(Color.decode("#7ACAC4"));
        PContactos1.telefono.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.correo.setBorderColor(Color.decode("#7ACAC4"));
        PContactos1.correo.setColorIcon(Color.decode("#7ACAC4"));
        PContactos1.correo.setForeground(Color.decode("#f5f5f5"));
        
        PContactos1.tabla.setColorBackgoundHead(Color.decode("#4CA18D"));
        PContactos1.tabla.setColorFilasBackgound1(Color.decode("#CFE2DB"));
        PContactos1.tabla.setColorFilasBackgound2(Color.decode("#B1D4C7"));
        PContactos1.tabla.setColorSelBackgound(Color.decode("#4CA18D"));
        PContactos1.jScrollPane1.setBackground(Color.decode("#f5f5f5"));
       
       //Info
       
        PInfo1.jPanel1.setBackground(Color.decode("#FFFFFF"));
              
        PCitas1.Titulo.setForeground(Color.decode("#7ACAC4"));
        PCitas1.Titulo.setColorIcon(Color.decode("#7ACAC4"));
        
        PInfo1.PanelS.setBackground(Color.decode("#7ACAC4"));
        PInfo1.BordeI.setBackground(Color.decode("#7ACAC4"));
        
        PInfo1.FondoP.setBackground(Color.decode("#FFFFFF"));   
        
        PInfo1.P1.setForeground(Color.decode("#000000"));
        PInfo1.P2.setForeground(Color.decode("#000000"));
        PInfo1.P3.setForeground(Color.decode("#000000"));
        PInfo1.P4.setForeground(Color.decode("#000000"));
        PInfo1.P5.setForeground(Color.decode("#000000"));
        PInfo1.P6.setForeground(Color.decode("#000000"));
        
    }//GEN-LAST:event_ModoClaroActionPerformed

    
    //===============================================================
                                
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconUno BCitas;
    private RSMaterialComponent.RSButtonMaterialIconUno BContactos;
    private RSMaterialComponent.RSButtonMaterialIconUno BExpedientes;
    private RSMaterialComponent.RSButtonMaterialIconUno BFirmas;
    private RSMaterialComponent.RSButtonMaterialIconUno BInfo;
    private RSMaterialComponent.RSButtonMaterialIconUno BSalir;
    private javax.swing.JMenu CalendarioM;
    private rojerusan.RSPanelCircleImage FPerfil;
    private rojerusan.RSMenuBar MenuBar;
    private javax.swing.JMenuItem ModoClaro;
    private javax.swing.JMenuItem ModoOscuro;
    private proyectofinal.PCitas PCitas1;
    private proyectofinal.PContactos PContactos1;
    private proyectofinal.PExpedientes PExpedientes1;
    private proyectofinal.PFirmas PFirmas1;
    private proyectofinal.PInfo PInfo1;
    private rojerusan.RSPanelsSlider Panel;
    private rspanelgradiente.RSPanelGradiente PanelLado;
    private javax.swing.JMenu TemasM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
