/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combobox_ventana;

/**
 *
 * @author Lord Shadow
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        
        initComponents();
        opciones.addItem("Sacar una espada.");
        opciones.addItem("Cubrirte con tu escudo.");
        opciones.addItem("Arrojar una roca.");
        opciones.addItem("Intentar entrar con sigilo");
        opciones.addItem("Usar la bolsa misteriosa.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonIconUno1 = new RSMaterialComponent.RSButtonIconUno();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        opciones = new RSMaterialComponent.RSComboBox();
        rSLabelImage1 = new rojeru_san.rslabel.RSLabelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(67, 160, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú de Opciones");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carlos Tavera - 1628839A");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        rSButtonIconUno1.setBackground(new java.awt.Color(67, 160, 71));
        rSButtonIconUno1.setBackgroundHover(new java.awt.Color(55, 131, 58));
        rSButtonIconUno1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconUno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconUno1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconUno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 110));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("custodiando la entrada al tesoro, decides...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eres un guerrero y tienes un gran Ogro enfrente de ti");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecciona una opción:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        opciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        opciones.setToolTipText("...");
        opciones.setColorArrow(new java.awt.Color(67, 160, 71));
        opciones.setColorBorde(new java.awt.Color(67, 160, 71));
        opciones.setColorFondo(new java.awt.Color(67, 160, 71));
        opciones.setColorListaItems(new java.awt.Color(64, 171, 70));
        opciones.setColorListaItemsTXT(new java.awt.Color(255, 255, 255));
        opciones.setColorSeleccion(new java.awt.Color(53, 123, 56));
        opciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionesItemStateChanged(evt);
            }
        });
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });
        jPanel1.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/combobox_ventana/imagen/4a033e3a1a170e02f6fac85646bba535.gif"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 730, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        res.setColumns(20);
        res.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 730, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_opcionesActionPerformed

    private void opcionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionesItemStateChanged
        String opc = (String) opciones.getSelectedItem();
               
        
        if(opc.equals("Sacar una espada.")){
            res.setText("Valientemente decides desenvainar tu espada y atacar,\n"
                      + "sin embargo no consigues hacerle ni un rasguño y a\n"
                      + "cambio recibes un martillazo en la cabeza.\n\n"
                      + "FIN DEL JUEGO\n");
        }
        
        if(opc.equals("Cubrirte con tu escudo.")){
            res.setText("Sabiamente decides defenderte con tu escudo, el Ogro\n"
                      + "se rie a carcajadas y te da una patada, rompiendo el\n"
                      + "escudo en dos.\n\n"
                      + "FIN DEL JUEGO\n");
        }
        
        if(opc.equals("Arrojar una roca.")){
            res.setText("Encuentras una piedra junto al camino, decides\n"
                      + "arrojarla con todas tus fuerzas a la cabeza del Ogro,\n"
                      + "pero la atrapa en el aire y te la lanza de vuelta.\n\n"
                      + "FIN DEL JUEGO\n");
        }
        
        if(opc.equals("Intentar entrar con sigilo")){
            res.setText("Piensas mejor las cosas y decides esconderte detras de\n"
                      + "una extraña roca, sin embargo eres un poco tonto y te\n"
                      + "das cuenta de que la roca era un oso.\n\n"
                      + "FIN DEL JUEGO\n");
        }
        
        if(opc.equals("Usar la bolsa misteriosa.")){
            res.setText("Recuerdas la bolsa que te dio tu abuela en la mañana\n"
                      + "la examinas un poco y ves que tiene una etiqueta: 'Pal susto'\n"
                      + "la abres con la sorpresa de que es un bolillo y decides\n"
                      + "compartirlo con el Ogro, pues tiene una peculiar forma de hablar\n"
                      + "y te das cuenta de que... ¡Es un Ogro chilango!\n\n"
                      + "FIN DEL JUEGO, ¡VICTORIA!\n");
        }
        
        
    }//GEN-LAST:event_opcionesItemStateChanged

    private void rSButtonIconUno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconUno1ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_rSButtonIconUno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSComboBox opciones;
    private RSMaterialComponent.RSButtonIconUno rSButtonIconUno1;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage1;
    private javax.swing.JTextArea res;
    // End of variables declaration//GEN-END:variables
}
